# Generated by Django 5.2 on 2025-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="website_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
