# Generated by Django 5.2 on 2025-05-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_website_website_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyses",
                to="website.website",
            ),
        ),
    ]
