# Generated by Django 5.2 on 2025-05-08 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_analysis_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="access_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
    ]
