# Generated by Django 5.2 on 2025-05-08 11:18

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Analysis = apps.get_model("website", "Analysis")
    for row in Analysis.objects.all():
        row.access_token = uuid.uuid4()
        row.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_analysis_access_token"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
