# Generated by Django 5.2 on 2025-05-08 11:18
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_auto_20250508_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="access_token",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
