# Generated by Django 5.2 on 2025-05-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_auto_20250508_1118"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name_plural": "Analyses"},
        ),
    ]
