# Generated by Django 5.2 on 2025-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_analysis_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="report_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
