# Generated by Django 5.2 on 2025-05-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_analysis_report_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="report_url",
            new_name="relative_url",
        ),
    ]
