# Generated by Django 5.2 on 2025-05-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_rename_report_url_analysis_relative_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="relative_url",
            new_name="report_url",
        ),
    ]
