# Generated by Django 5.2 on 2025-05-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_rename_relative_url_analysis_report_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.PositiveIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("last_emailed", models.DateTimeField(blank=True, null=True)),
                ("bounced", models.BooleanField(default=False)),
                ("opt_out", models.BooleanField(default=False)),
            ],
        ),
    ]
