# Generated by Django 5.1.1 on 2025-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='date_earned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
