# Generated by Django 5.1.1 on 2025-02-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_qualification_date_earned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
