# Generated by Django 5.1.6 on 2025-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
