# Generated by Django 5.1.6 on 2025-04-13 01:43

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpostpage",
            old_name="intro",
            new_name="summary",
        ),
        migrations.RemoveField(
            model_name="blogpostpage",
            name="date",
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="date_published",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="thumbnail",
            field=models.ImageField(default="/", upload_to="media/blog/images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpostpage",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("captioned_image", 3), ("image", 4), ("code", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("caption", 2)]],
                        {"icon": "image"},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("bash", "Bash"),
                            ]
                        },
                    ),
                    6: ("wagtail.blocks.TextBlock", (), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 5), ("code", 6)]],
                        {"icon": "code"},
                    ),
                },
            ),
        ),
    ]
