# Generated by Django 5.2 on 2025-05-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpostpage_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostpage",
            name="date_published",
        ),
    ]
