# Generated by Django 5.2 on 2025-05-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_booking_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
