# Generated by Django 5.2 on 2025-06-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0003_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.CharField(choices=[], max_length=5)),
                ("email", models.EmailField(max_length=254)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("date", "time")},
            },
        ),
    ]
