# Generated by Django 5.2 on 2025-06-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
