# Generated by Django 5.2 on 2025-05-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchparameter",
            name="last_run_thomson",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
