# Generated by Django 5.2 on 2025-07-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("email_opt_out", models.BooleanField(default=False)),
                ("phone", models.CharField()),
                ("website", models.URLField()),
                ("company", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("former", "Former"),
                        ],
                        default="lead",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medium", models.CharField(default="email", max_length=11)),
                ("made_on", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="vertical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.vertical"
            ),
        ),
    ]
