# Generated by Django 5.1.6 on 2025-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="medium",
            field=models.CharField(
                choices=[
                    ("ph", "Phone"),
                    ("em", "Email"),
                    ("vc", "Video Call"),
                    ("li", "LinkedIn"),
                ],
                default="di",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
