# Generated by Django 5.2 on 2025-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_contact_company_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertical",
            name="name",
            field=models.CharField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="communication",
            unique_together={("contact", "made_on")},
        ),
    ]
