# Generated by Django 5.1.6 on 2025-04-10 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_interaction_medium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.RemoveField(
            model_name="task",
            name="company",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
    ]
