# Generated by Django 5.1.6 on 2025-04-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_contact_linkedin_contact_status_website_proitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="n_broken_links",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="website",
            name="n_bugs",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
