# Generated by Django 5.2 on 2025-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_website_n_broken_links_alter_website_n_bugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proitem",
            name="website",
        ),
        migrations.RemoveField(
            model_name="website",
            name="contact",
        ),
        migrations.AddField(
            model_name="contact",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ConItem",
        ),
        migrations.DeleteModel(
            name="ProItem",
        ),
        migrations.DeleteModel(
            name="Website",
        ),
    ]
