# Generated by Django 5.2 on 2025-05-03 13:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_remove_proitem_website_remove_website_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="website",
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("url", models.URLField()),
                ("ssl_certificate", models.BooleanField(default=False)),
                ("load_time_under_3_seconds", models.BooleanField(default=False)),
                ("images_optimized_for_loading", models.BooleanField(default=False)),
                ("n_broken_links", models.IntegerField(blank=True, default=0)),
                ("looks_good_on_mobile", models.BooleanField(default=False)),
                ("readable_without_zooming", models.BooleanField(default=False)),
                ("elements_overflow_off_screen", models.BooleanField(default=False)),
                ("meta_titles_and_descriptions", models.BooleanField(default=False)),
                ("indexed_by_google", models.BooleanField(default=False)),
                ("basic_keyword_targeting", models.BooleanField(default=False)),
                ("updated_in_last_3_months", models.BooleanField(default=False)),
                ("clear_contact_info", models.BooleanField(default=False)),
                ("n_bugs", models.IntegerField(blank=True, default=0)),
                (
                    "contact",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="crm.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "website",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pros",
                        to="crm.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "website",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cons",
                        to="crm.website",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
