# Generated by Django 5.2 on 2025-07-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_communication_communication_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communication",
            name="subject",
            field=models.CharField(blank=True, null=True),
        ),
    ]
