# Generated by Django 5.1.6 on 2025-04-29 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_remove_interaction_date_remove_interaction_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interaction",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="interaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interaction",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
