# Generated by Django 5.2 on 2025-05-06 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_remove_contact_website_website_proitem_conitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proitem",
            name="website",
        ),
        migrations.RemoveField(
            model_name="website",
            name="basic_keyword_targeting",
        ),
        migrations.RemoveField(
            model_name="website",
            name="clear_contact_info",
        ),
        migrations.RemoveField(
            model_name="website",
            name="elements_overflow_off_screen",
        ),
        migrations.RemoveField(
            model_name="website",
            name="images_optimized_for_loading",
        ),
        migrations.RemoveField(
            model_name="website",
            name="indexed_by_google",
        ),
        migrations.RemoveField(
            model_name="website",
            name="load_time_under_3_seconds",
        ),
        migrations.RemoveField(
            model_name="website",
            name="looks_good_on_mobile",
        ),
        migrations.RemoveField(
            model_name="website",
            name="meta_titles_and_descriptions",
        ),
        migrations.RemoveField(
            model_name="website",
            name="n_broken_links",
        ),
        migrations.RemoveField(
            model_name="website",
            name="n_bugs",
        ),
        migrations.RemoveField(
            model_name="website",
            name="readable_without_zooming",
        ),
        migrations.RemoveField(
            model_name="website",
            name="ssl_certificate",
        ),
        migrations.RemoveField(
            model_name="website",
            name="updated_in_last_3_months",
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="website",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="website",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="ConItem",
        ),
        migrations.DeleteModel(
            name="ProItem",
        ),
    ]
