# Generated by Django 5.2 on 2025-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_remove_proitem_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
