# Generated by Django 5.2 on 2025-05-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_contact_email_alter_contact_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
