# Generated by Django 5.2 on 2025-05-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_alter_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="search_term",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
