# Generated by Django 5.2 on 2025-05-16 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_contact_search_term"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("site_audit", "Website Audit"),
                            ("client_analysis", "Client Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "medium",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("social_media", "Social Media"),
                            ("direct_mail", "Direct Mail"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("pain_points", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="website",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="service",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="company",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="service",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="template",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="company",
        ),
        migrations.RemoveField(
            model_name="task",
            name="related_to",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="related_deal",
        ),
        migrations.RemoveField(
            model_name="deliverable",
            name="service",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="company",
        ),
        migrations.RemoveField(
            model_name="interactionattachment",
            name="interaction",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="company",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="service",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="template",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="packagetier",
            name="pricing_option",
        ),
        migrations.RemoveField(
            model_name="service",
            name="package_tier",
        ),
        migrations.RemoveField(
            model_name="pricingoption",
            name="service_type",
        ),
        migrations.RemoveField(
            model_name="service",
            name="pricing_option",
        ),
        migrations.RemoveField(
            model_name="service",
            name="company",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_type",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="service",
        ),
        migrations.AlterModelOptions(
            name="website",
            options={},
        ),
        migrations.RemoveField(
            model_name="website",
            name="sort_order",
        ),
        migrations.AddField(
            model_name="website",
            name="campaign",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="client",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="website",
            name="lead",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("report_url", models.URLField(blank=True, null=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="crm.website",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analyses",
            },
        ),
        migrations.CreateModel(
            name="CampaignMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="crm.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("ms", "Ms."),
                            ("dr", "Dr."),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(blank=True, max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("cl", "Client")],
                        default=("cl", "Client"),
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_term",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("audit_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("aware", "Aware"),
                            ("interested", "Interested"),
                            ("engaged", "Engaged"),
                            ("converted", "Converted"),
                            ("cold", "Cold"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                ("first_emailed_on", models.DateTimeField(blank=True, null=True)),
                ("email_bounced", models.BooleanField(default=False)),
                ("email_opened", models.BooleanField(default=False)),
                ("follow_up_emailed_on", models.DateTimeField(blank=True, null=True)),
                ("follow_up_email_bounced", models.BooleanField(default=False)),
                ("follow_up_email_opened", models.BooleanField(default=False)),
                ("audit_viewed", models.BooleanField(default=False)),
                ("call_booked", models.BooleanField(default=False)),
                ("converted", models.BooleanField(default=False)),
                ("opt_out", models.BooleanField(default=False)),
                (
                    "opt_out_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_emailed", "First Emailed"),
                            ("follow_up_emailed", "Follow Up Emailed"),
                            ("audit_viewed", "Audit Viewed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="crm.campaign",
                    ),
                ),
                (
                    "search_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.location",
                    ),
                ),
                (
                    "search_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.searchterm",
                    ),
                ),
                (
                    "vertical",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.vertical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.campaign"
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("intro", "Intro"),
                            ("score", "Score"),
                            ("closing", "Closing"),
                            ("farewell", "Farewell"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric", models.CharField(blank=True, max_length=50, null=True)),
                ("score_band", models.CharField(blank=True, max_length=50, null=True)),
                ("active", models.BooleanField(default=True)),
                ("message", models.TextField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptedOutEmails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=200, unique=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "opt_out_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first_emailed", "First Emailed"),
                            ("follow_up_emailed", "Follow Up Emailed"),
                            ("audit_viewed", "Audit Viewed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opted_out_emails",
                        to="crm.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignSearchParemeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_parameters",
                        to="crm.campaign",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.location",
                    ),
                ),
                (
                    "search_term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.searchterm",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="searchterm",
            name="veritcal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_terms",
                to="crm.vertical",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="vertical",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="crm.vertical",
            ),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Contract",
        ),
        migrations.DeleteModel(
            name="ContractTemplate",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="Deal",
        ),
        migrations.DeleteModel(
            name="Deliverable",
        ),
        migrations.DeleteModel(
            name="Interaction",
        ),
        migrations.DeleteModel(
            name="InteractionAttachment",
        ),
        migrations.DeleteModel(
            name="InvoiceTemplate",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceLineItem",
        ),
        migrations.DeleteModel(
            name="PackageTier",
        ),
        migrations.DeleteModel(
            name="PricingOption",
        ),
        migrations.DeleteModel(
            name="ServiceType",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="TimeEntry",
        ),
    ]
