# Generated by Django 5.2 on 2025-05-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_client_company_delete_company"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
