# Generated by Django 5.2 on 2025-05-17 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_delete_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, max_length=255)),
                ("town", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(default="UK", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BouncedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("hard", "Hard"), ("soft", "Soft")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignEmailContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("intro", "Intro"),
                            ("score", "Score"),
                            ("closing", "Closing"),
                            ("farewell", "Farewell"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("acc", "Accessibility"),
                            ("bp", "Best Practices"),
                            ("per", "Performance"),
                            ("seo", "SEO"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "core_score_band",
                    models.IntegerField(
                        choices=[(50, "low"), (90, "mid"), (100, "high")], null=True
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("message", models.TextField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "headquarters",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.address",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mr", "Mr."),
                            ("mrs", "Mrs."),
                            ("ms", "Ms."),
                            ("dr", "Dr."),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactEmails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact_emails",
            },
        ),
        migrations.CreateModel(
            name="ContactEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact_entities",
            },
        ),
        migrations.CreateModel(
            name="ContactPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact_phone_numbers",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("last_emailed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.campaign"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("name", models.CharField(max_length=255)),
                ("is_company", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntityAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.address"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entity_addresses",
            },
        ),
        migrations.CreateModel(
            name="EntityEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.email"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entity_emails",
            },
        ),
        migrations.CreateModel(
            name="EntityPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entity_phone_numbers",
            },
        ),
        migrations.CreateModel(
            name="EntityWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entity_websites",
            },
        ),
        migrations.CreateModel(
            name="LeadEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.email"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lead_emails",
            },
        ),
        migrations.CreateModel(
            name="LeadEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lead_entities",
            },
        ),
        migrations.CreateModel(
            name="LeadPhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lead_phone_numbers",
            },
        ),
        migrations.CreateModel(
            name="LighthouseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "access_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("report_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Lighthouse Analyses",
            },
        ),
        migrations.CreateModel(
            name="LinkEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField()),
                ("time_spent_seconds", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpenedEmailEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("n", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="OptedOutEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mobile", "Mobile"),
                            ("landline", "Landline"),
                            ("work", "Work"),
                            ("fax", "Fax"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseEmailEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_at", models.DateTimeField()),
                ("content", models.TextField()),
                ("is_positive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="SearchLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.campaign"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "campaign")},
            },
        ),
        migrations.CreateModel(
            name="SentCampaignEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(1, "Initial"), (2, "Follow-Up")]),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opt_out_after",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("first", "First Email"),
                            ("second", "Follow-Up Email"),
                            ("link view", "Link Viewed"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_campaign_emails",
                        to="crm.campaign",
                    ),
                ),
                (
                    "campaign_email_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent",
                        to="crm.campaignemailcontent",
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.email"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="website",
        ),
        migrations.RemoveField(
            model_name="campaignevent",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="campaignevent",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="campaignmetric",
            name="campaign",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="search_location",
        ),
        migrations.RemoveField(
            model_name="message",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="optedoutemails",
            name="campaign",
        ),
        migrations.RenameField(
            model_name="searchterm",
            old_name="veritcal",
            new_name="vertical",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="audit_url",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="audit_viewed",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="call_booked",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="company",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="converted",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="email",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="email_bounced",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="email_opened",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="first_emailed_on",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="follow_up_email_bounced",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="follow_up_email_opened",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="follow_up_emailed_on",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="opt_out",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="opt_out_after",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="search_term",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="status",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="vertical",
        ),
        migrations.RemoveField(
            model_name="searchterm",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="searchterm",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="vertical",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="vertical",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="website",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="website",
            name="client",
        ),
        migrations.RemoveField(
            model_name="website",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="website",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="website",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="lead",
            name="job_title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="contactemails",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.email"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="search_term",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.searchterm",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="vertical",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.vertical",
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="contactentity",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="entity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="entityaddress",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="entityemail",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="entityphonenumber",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="entitywebsite",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="entitywebsite",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.website"
            ),
        ),
        migrations.AddField(
            model_name="leademail",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
            ),
        ),
        migrations.AddField(
            model_name="leadentity",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AddField(
            model_name="leadentity",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
            ),
        ),
        migrations.AddField(
            model_name="leadphonenumber",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
            ),
        ),
        migrations.AddField(
            model_name="lighthouseanalysis",
            name="website",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lighthouse_analyses",
                to="crm.website",
            ),
        ),
        migrations.AddField(
            model_name="linkengagement",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.engagement"
            ),
        ),
        migrations.AddField(
            model_name="openedemailengagement",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.engagement"
            ),
        ),
        migrations.AddField(
            model_name="leadphonenumber",
            name="phone_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.phonenumber"
            ),
        ),
        migrations.AddField(
            model_name="entityphonenumber",
            name="phone_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.phonenumber"
            ),
        ),
        migrations.AddField(
            model_name="contactphonenumber",
            name="phone_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.phonenumber"
            ),
        ),
        migrations.AddField(
            model_name="responseemailengagement",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.engagement"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.searchlocation",
            ),
        ),
        migrations.AlterField(
            model_name="campaignsearchparemeter",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.searchlocation",
            ),
        ),
        migrations.AddField(
            model_name="responseemailengagement",
            name="sent_campaign_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.sentcampaignemail"
            ),
        ),
        migrations.AddField(
            model_name="optedoutemail",
            name="sent_campaign_email",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.sentcampaignemail",
            ),
        ),
        migrations.AddField(
            model_name="openedemailengagement",
            name="sent_campaign_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.sentcampaignemail"
            ),
        ),
        migrations.AddField(
            model_name="linkengagement",
            name="sent_campaign_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.sentcampaignemail",
            ),
        ),
        migrations.AddField(
            model_name="bouncedemail",
            name="sent_campaign_email",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.sentcampaignemail",
            ),
        ),
        migrations.DeleteModel(
            name="Analysis",
        ),
        migrations.DeleteModel(
            name="CampaignEvent",
        ),
        migrations.DeleteModel(
            name="CampaignMetric",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="OptedOutEmails",
        ),
        migrations.AlterUniqueTogether(
            name="contactemails",
            unique_together={("contact", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="contactentity",
            unique_together={("contact", "entity")},
        ),
        migrations.AlterUniqueTogether(
            name="entityaddress",
            unique_together={("entity", "address")},
        ),
        migrations.AlterUniqueTogether(
            name="entityemail",
            unique_together={("entity", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="entitywebsite",
            unique_together={("entity", "website")},
        ),
        migrations.AlterUniqueTogether(
            name="leademail",
            unique_together={("lead", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="leadentity",
            unique_together={("lead", "entity")},
        ),
        migrations.AlterUniqueTogether(
            name="leadphonenumber",
            unique_together={("lead", "phone_number")},
        ),
        migrations.AlterUniqueTogether(
            name="entityphonenumber",
            unique_together={("entity", "phone_number")},
        ),
        migrations.AlterUniqueTogether(
            name="contactphonenumber",
            unique_together={("contact", "phone_number")},
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
