# Generated by Django 5.2 on 2025-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_address_bouncedemail_campaignemailcontent_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactEmails",
            new_name="ContactEmail",
        ),
        migrations.AddField(
            model_name="contact",
            name="emails",
            field=models.ManyToManyField(through="crm.ContactEmail", to="crm.email"),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_numbers",
            field=models.ManyToManyField(
                through="crm.ContactPhoneNumber", to="crm.phonenumber"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="addresses",
            field=models.ManyToManyField(through="crm.EntityAddress", to="crm.address"),
        ),
        migrations.AddField(
            model_name="entity",
            name="contacts",
            field=models.ManyToManyField(through="crm.ContactEntity", to="crm.contact"),
        ),
        migrations.AddField(
            model_name="entity",
            name="emails",
            field=models.ManyToManyField(through="crm.EntityEmail", to="crm.email"),
        ),
        migrations.AddField(
            model_name="entity",
            name="leads",
            field=models.ManyToManyField(through="crm.LeadEntity", to="crm.lead"),
        ),
        migrations.AddField(
            model_name="entity",
            name="phone_numbers",
            field=models.ManyToManyField(
                through="crm.EntityPhoneNumber", to="crm.phonenumber"
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="websites",
            field=models.ManyToManyField(through="crm.EntityWebsite", to="crm.website"),
        ),
        migrations.AddField(
            model_name="lead",
            name="emails",
            field=models.ManyToManyField(through="crm.LeadEmail", to="crm.email"),
        ),
        migrations.AddField(
            model_name="lead",
            name="phone_numbers",
            field=models.ManyToManyField(
                through="crm.LeadPhoneNumber", to="crm.phonenumber"
            ),
        ),
    ]
