# Generated by Django 5.2 on 2025-05-20 11:05

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_rename_contactemails_contactemail_contact_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactemail",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="contactentity",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="contactphonenumber",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="entityaddress",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="entityemail",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="entityphonenumber",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="entitywebsite",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="leademail",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="leadentity",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="leadphonenumber",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="contact",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
            ),
        ),
        migrations.AlterField(
            model_name="contactentity",
            name="contact",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
            ),
        ),
        migrations.AlterField(
            model_name="contactphonenumber",
            name="contact",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
            ),
        ),
        migrations.AlterField(
            model_name="entityaddress",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AlterField(
            model_name="entityemail",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AlterField(
            model_name="entityphonenumber",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AlterField(
            model_name="entitywebsite",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
        ),
        migrations.AlterField(
            model_name="leademail",
            name="lead",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
            ),
        ),
        migrations.AlterField(
            model_name="leadentity",
            name="lead",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
            ),
        ),
        migrations.AlterField(
            model_name="leadphonenumber",
            name="lead",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
            ),
        ),
        migrations.AlterField(
            model_name="searchlocation",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_locations",
                to="crm.campaign",
            ),
        ),
    ]
