# Generated by Django 5.2 on 2025-05-20 14:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_contactemail_sort_order_contactentity_sort_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="emails",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone_numbers",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="location",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="search_term",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="emails",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="phone_numbers",
        ),
        migrations.AddField(
            model_name="entity",
            name="campaign_search_parameter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.campaignsearchparemeter",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[("mr", "Mr."), ("mrs", "Mrs."), ("ms", "Ms."), ("dr", "Dr.")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[("mr", "Mr."), ("mrs", "Mrs."), ("ms", "Ms."), ("dr", "Dr.")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactemail",
            name="contact",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_emails",
                to="crm.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contactentity",
            name="contact",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_entities",
                to="crm.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contactphonenumber",
            name="contact",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_phone_numbers",
                to="crm.contact",
            ),
        ),
        migrations.AlterField(
            model_name="entity",
            name="vertical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.vertical",
            ),
        ),
        migrations.AlterField(
            model_name="entityaddress",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_addresses",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityemail",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_emails",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityphonenumber",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_phone_numbers",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entitywebsite",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_websites",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="leademail",
            name="lead",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_emails",
                to="crm.lead",
            ),
        ),
        migrations.AlterField(
            model_name="leadentity",
            name="lead",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_entities",
                to="crm.lead",
            ),
        ),
        migrations.AlterField(
            model_name="leadphonenumber",
            name="lead",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_phone_numbers",
                to="crm.lead",
            ),
        ),
    ]
