# Generated by Django 5.2 on 2025-05-20 14:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0017_remove_contact_emails_remove_contact_phone_numbers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
                (
                    "entity",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_contacts",
                        to="crm.entity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact_entities",
                "unique_together": {("contact", "entity")},
            },
        ),
    ]
