# Generated by Django 5.2 on 2025-05-20 14:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_entitycontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "entity",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_leads",
                        to="crm.entity",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lead_entities",
                "unique_together": {("lead", "entity")},
            },
        ),
    ]
