# Generated by Django 5.2 on 2025-05-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_entitylead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="addresses",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="emails",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="leads",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="phone_numbers",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="websites",
        ),
        migrations.AddField(
            model_name="lead",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("aware", "Aware"),
                    ("interested", "Interested"),
                    ("engaged", "Engaged"),
                    ("converted", "Converted"),
                    ("cold", "Cold"),
                ],
                default="aware",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
