# Generated by Django 5.2 on 2025-05-20 16:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_remove_entity_addresses_remove_entity_contacts_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchlocation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bouncedemail",
            name="email",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.email"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="optedoutemail",
            name="email",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.email"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="searchlocation",
            name="type",
            field=models.CharField(default="to", max_length=2),
        ),
        migrations.AlterField(
            model_name="bouncedemail",
            name="sent_campaign_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crm.sentcampaignemail",
            ),
        ),
        migrations.AlterField(
            model_name="bouncedemail",
            name="type",
            field=models.CharField(
                choices=[("hard", "Hard"), ("soft", "Soft")],
                default="hard",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="optedoutemail",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="searchlocation",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="searchterm",
            name="vertical",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_terms",
                to="crm.vertical",
            ),
        ),
        migrations.CreateModel(
            name="CampaignSearchLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "campaign",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_search_locations",
                        to="crm.campaign",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.searchlocation",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="searchlocation",
            name="campaign",
        ),
    ]
