# Generated by Django 5.2 on 2025-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_alter_searchlocation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="bounced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="email",
            name="opted_out",
            field=models.BooleanField(default=False),
        ),
    ]
