# Generated by Django 5.2 on 2025-05-21 12:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0023_company_remove_campaignsearchlocations_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="entity",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="entity",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EntityContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
                (
                    "entity",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
                    ),
                ),
            ],
        ),
    ]
