# Generated by Django 5.2 on 2025-05-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0024_company_entity_lead_entity_entitycontact"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entityaddress",
            unique_together={("entity", "address")},
        ),
        migrations.AlterUniqueTogether(
            name="entitycontact",
            unique_together={("entity", "contact")},
        ),
        migrations.AlterUniqueTogether(
            name="entityemail",
            unique_together={("entity", "email")},
        ),
        migrations.AlterUniqueTogether(
            name="entityphonenumber",
            unique_together={("entity", "phone_number")},
        ),
        migrations.AlterUniqueTogether(
            name="entitysearchlocation",
            unique_together={("entity", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="entityvertical",
            unique_together={("entity", "vertical")},
        ),
        migrations.AlterUniqueTogether(
            name="entitywebsite",
            unique_together={("entity", "website")},
        ),
    ]
