# Generated by Django 5.2 on 2025-05-21 14:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0025_alter_entityaddress_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="entity",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CompanyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.entity"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.contact"
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "contact")},
            },
        ),
        migrations.DeleteModel(
            name="EntityContact",
        ),
    ]
