# Generated by Django 5.2 on 2025-05-22 10:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0026_contact_entity_companycontact_delete_entitycontact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignemailcontent",
            name="campaign",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_content",
                to="crm.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="campaignsearchlocation",
            name="campaign",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_locations",
                to="crm.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.entity",
            ),
        ),
    ]
