# Generated by Django 5.2 on 2025-05-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0027_alter_campaignemailcontent_campaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsearchparameter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
