# Generated by Django 5.2 on 2025-05-22 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0028_campaignsearchparameter_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="medium",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("social_media", "Social Media"),
                    ("direct_mail", "Direct Mail"),
                ],
                default="email",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 22, 12, 54, 28, 539195, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="type",
            field=models.CharField(
                choices=[
                    ("site_audit", "Website Audit"),
                    ("client_analysis", "Client Analysis"),
                ],
                default="site_audit",
                max_length=50,
            ),
        ),
    ]
