# Generated by Django 5.2 on 2025-05-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0029_alter_campaign_end_date_alter_campaign_medium_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 22, 12, 58, 23, 21572, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
