# Generated by Django 5.2 on 2025-05-22 18:26

import datetime
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0030_alter_campaign_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 22, 18, 26, 18, 668407, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="campaignsearchparameter",
            name="last_run",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companycontact",
            name="company",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityaddress",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityemail",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityphonenumber",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entitysearchlocation",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_locations",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entityvertical",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertical",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="entitywebsite",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="websites",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
