# Generated by Django 5.2 on 2025-05-22 23:07

import datetime
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0031_alter_campaign_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 22, 23, 7, 41, 379991, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="EmailContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("greeting", models.TextField(blank=True)),
                ("intro", models.TextField(blank=True)),
                ("main", models.TextField(blank=True)),
                ("closing", models.TextField(blank=True)),
                ("farewell", models.TextField(blank=True)),
                (
                    "campaign",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_content",
                        to="crm.campaign",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BulletContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("accessibility", "Accessibility"),
                            ("best_practices", "Best Practices"),
                            ("seo", "SEO"),
                            ("performance", "Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "score_range",
                    models.CharField(
                        choices=[("l", "Low"), ("m", "Mid"), ("h", "High")],
                        max_length=1,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "email_content",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_contents",
                        to="crm.emailcontent",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="CampaignEmailContent",
        ),
    ]
