# Generated by Django 5.2 on 2025-05-22 23:24

import datetime
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0032_alter_campaign_start_date_emailcontent_bulletcontent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 22, 23, 24, 33, 573266, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("a", "Aware"),
                    ("i", "Interested"),
                    ("e", "Engaged"),
                    ("c", "Converted"),
                    ("x", "Cold"),
                ],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="EmailContentMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("s", "Sent"),
                            ("d", "Deliveries"),
                            ("o", "Opens"),
                            ("l", "Link Clicks"),
                            ("b", "Bounces"),
                            ("x", "Opt-Outs"),
                        ],
                        max_length=1,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_content",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="crm.emailcontent",
                    ),
                ),
            ],
            options={
                "unique_together": {("email_content", "metric")},
            },
        ),
    ]
