# Generated by Django 5.2 on 2025-05-23 00:35

import datetime
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0033_alter_campaign_start_date_alter_lead_status_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="emailcontentmetric",
            name="action",
            field=models.CharField(
                choices=[
                    ("s", "Sent"),
                    ("d", "Deliveries"),
                    ("o", "Opens"),
                    ("1", "First Opens"),
                    ("l", "Link Clicks"),
                    ("b", "Bounces"),
                    ("x", "Opt-Outs"),
                ],
                default="s",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="emailcontentmetric",
            unique_together={("email_content", "action")},
        ),
        migrations.AddField(
            model_name="emailcontent",
            name="stage",
            field=models.CharField(
                choices=[("i", "Initial"), ("f", "Follow-Up")],
                default="i",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 23, 0, 34, 49, 71203, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="entityvertical",
            name="entity",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verticals",
                to="crm.entity",
            ),
        ),
        migrations.RemoveField(
            model_name="emailcontentmetric",
            name="metric",
        ),
        migrations.CreateModel(
            name="CampaignMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("s", "Sent"),
                            ("d", "Deliveries"),
                            ("o", "Opens"),
                            ("1", "First Opens"),
                            ("l", "Link Clicks"),
                            ("b", "Bounces"),
                            ("x", "Opt-Outs"),
                        ],
                        max_length=1,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="crm.campaign",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "action")},
            },
        ),
        migrations.CreateModel(
            name="CampaignSearchParameterMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("s", "Sent"),
                            ("d", "Deliveries"),
                            ("o", "Opens"),
                            ("1", "First Opens"),
                            ("l", "Link Clicks"),
                            ("b", "Bounces"),
                            ("x", "Opt-Outs"),
                        ],
                        max_length=1,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign_search_parameter",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="crm.campaignsearchparameter",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign_search_parameter", "action")},
            },
        ),
    ]
