# Generated by Django 5.2 on 2025-05-23 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0034_alter_emailcontentmetric_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 23, 0, 47, 17, 327315, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("a", "Aware"),
                    ("i", "Interested"),
                    ("e", "Engaged"),
                    ("c", "Converted"),
                    ("x", "Cold"),
                ],
                default="a",
                max_length=1,
            ),
        ),
    ]
