# Generated by Django 5.2 on 2025-05-23 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0035_alter_campaign_start_date_alter_lead_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 23, 0, 51, 7, 356938, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="emailcontent",
            name="stage",
            field=models.CharField(
                choices=[("i", "Initial"), ("f", "Follow-Up")],
                default="i",
                max_length=1,
            ),
        ),
    ]
