# Generated by Django 5.2 on 2025-05-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0036_alter_campaign_start_date_alter_emailcontent_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
