# Generated by Django 5.2 on 2025-05-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0038_alter_campaign_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Aware"),
                    ("i", "Interested"),
                    ("e", "Engaged"),
                    ("c", "Converted"),
                    ("x", "Cold"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
