# Generated by Django 5.2 on 2025-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0040_lead_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignmetric",
            name="action",
            field=models.CharField(
                choices=[
                    ("s", "Sent"),
                    ("d", "Deliveries"),
                    ("o", "Opens"),
                    ("1", "First Opens"),
                    ("l", "Link Clicks"),
                    ("b", "Bounces"),
                    ("x", "Opt-Outs"),
                    ("+", "Leads Added"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="campaignsearchparametermetric",
            name="action",
            field=models.CharField(
                choices=[
                    ("s", "Sent"),
                    ("d", "Deliveries"),
                    ("o", "Opens"),
                    ("1", "First Opens"),
                    ("l", "Link Clicks"),
                    ("b", "Bounces"),
                    ("x", "Opt-Outs"),
                    ("+", "Leads Added"),
                ],
                max_length=1,
            ),
        ),
    ]
