# Generated by Django 5.2 on 2025-05-23 06:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0042_entitycampaign_entitysearchterm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painpoint",
            name="vertical",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="painpoints",
                to="crm.vertical",
            ),
        ),
    ]
