# Generated by Django 5.2 on 2025-05-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0043_alter_painpoint_vertical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcontent",
            name="main",
            field=models.TextField(blank=True, null=True),
        ),
    ]
