# Generated by Django 5.2 on 2025-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0044_alter_emailcontent_main"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignsearchlocation",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="campaignsearchlocation",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
