# Generated by Django 5.2 on 2025-05-23 06:59

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0045_alter_campaignsearchlocation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachemail",
            name="outreach",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email",
                to="crm.outreach",
            ),
        ),
        migrations.AlterField(
            model_name="outreachwebsite",
            name="outreach",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="website",
                to="crm.outreach",
            ),
        ),
    ]
