# Generated by Django 5.2 on 2025-05-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0046_alter_outreachemail_outreach_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchlocation",
            name="type",
            field=models.CharField(
                choices=[("to", "Town"), ("pc", "Post Code")],
                default="to",
                max_length=2,
            ),
        ),
    ]
