# Generated by Django 5.2 on 2025-05-23 07:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0047_alter_searchlocation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycontact",
            name="company",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="crm.company",
            ),
        ),
    ]
