# Generated by Django 5.2 on 2025-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0048_alter_companycontact_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcontent",
            name="subject",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="campaign_search_param",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
