# Generated by Django 5.2 on 2025-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0049_emailcontent_subject_lead_campaign_search_param"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcontent",
            name="link_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="outreach",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
