# Generated by Django 5.2 on 2025-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0050_emailcontent_link_text_alter_outreach_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="url",
            field=models.URLField(default="", unique=True),
            preserve_default=False,
        ),
    ]
