# Generated by Django 5.2 on 2025-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0051_alter_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignsearchparameter",
            name="location_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignsearchparameter",
            name="search_term_pk",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
