# Generated by Django 5.2 on 2025-06-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0052_campaignsearchparameter_location_pk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="companycontact",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="crm.contact",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="crm.entity",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="entity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="crm.entity",
            ),
        ),
    ]
