# Generated by Django 5.1.6 on 2025-04-13 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                (
                    "first_visited",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_visited", models.DateTimeField(auto_now=True)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("visited_pages", models.JSONField(default=list)),
                ("browser", models.CharField(blank=True, max_length=100)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("device", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
